FROM bonita:latest

LABEL maintainer="Hector Huaranga <hahuaranga@indracompany.com>"
MAINTAINER Hector Huaranga <hahuaranga@indracompany.com>

ENV DB_VENDOR=postgres
ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_NAME=bonita
ENV DB_USER=bonita
ENV DB_PASS=bpm
ENV BIZ_DB_NAME=business_data
ENV BIZ_DB_USER=business_data
ENV BIZ_DB_PASS=bpm
ENV TENANT_LOGIN=tech_user
ENV TENANT_PASSWORD=secret
ENV PLATFORM_LOGIN=pfadmin
ENV PLATFORM_PASSWORD=pfsecret

# Actualiza el índice de los paquetes y luego actualiza todos los paquetes instalados
RUN apk update && apk upgrade --no-cache

# add certificate
COPY cert/ /cert



# Establece variables de entorno necesarias
ENV BONITA_HOME=/opt/bonita

# Copia el script de configuración en el contenedor
COPY config-bonita.sh /config-bonita.sh

# Fix Dos2Unix
RUN /bin/sed -i 's/\r$//' /config-bonita.sh

# Da permisos de ejecución al script
RUN chmod +x /config-bonita.sh

# Ejecuta el script de configuración
#RUN /config-bonita.sh

########### End Customization

# Copy the startup script into the container
COPY wait-for-postgres.sh /usr/local/bin/wait-for-postgres.sh

# Fix Dos2Unix
RUN /bin/sed -i 's/\r$//' /usr/local/bin/wait-for-postgres.sh

# Make the script executable
RUN chmod +x /usr/local/bin/wait-for-postgres.sh

# Set the entrypoint to the script
ENTRYPOINT ["/bin/bash","/usr/local/bin/wait-for-postgres.sh"]

# Use the original command for Bonita
CMD ["/opt/files/startup.sh", "/opt/bonita/server/bin/catalina.sh", "run"]